### ISSUE TITLE
Not working in the stock Android 10

### ISSUE THREAD

**Issue by eviIgenius** [V3rB0se/Alynx-RMX1971#1]
Hey Developer!!

Firstly thanks for making the kernel, I was trying the same on my realme 5 pro RMX1971, Android 10 (Downgraded) RMX1971EX_11_OTA_1150_all_006aZofuEOvC Version, but the same didn't worked,
Can you let me know which ROM (Android Version and the name of ROM) are you using or on which ROM it works the best.

Thanks and Regards

**Comment by V3rB0se** [comment]
Android 12
